################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../RFID_display.c \
../app.c \
../i2c_init.c \
../main.c \
../rc522.c \
../rtc3231.c \
../ssd1306.c 

OBJS += \
./RFID_display.o \
./app.o \
./i2c_init.o \
./main.o \
./rc522.o \
./rtc3231.o \
./ssd1306.o 

C_DEPS += \
./RFID_display.d \
./app.d \
./i2c_init.d \
./main.d \
./rc522.d \
./rtc3231.d \
./ssd1306.d 


# Each subdirectory must supply rules for building sources it contributes
RFID_display.o: ../RFID_display.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\config" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\autogen" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32MG21/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -c -fmessage-length=0 -MMD -MP -MF"RFID_display.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app.o: ../app.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\config" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\autogen" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32MG21/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -c -fmessage-length=0 -MMD -MP -MF"app.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

i2c_init.o: ../i2c_init.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\config" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\autogen" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32MG21/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -c -fmessage-length=0 -MMD -MP -MF"i2c_init.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\config" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\autogen" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32MG21/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -c -fmessage-length=0 -MMD -MP -MF"main.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rc522.o: ../rc522.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\config" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\autogen" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32MG21/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -c -fmessage-length=0 -MMD -MP -MF"rc522.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

rtc3231.o: ../rtc3231.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\config" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\autogen" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32MG21/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -c -fmessage-length=0 -MMD -MP -MF"rtc3231.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

ssd1306.o: ../ssd1306.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\config" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1\autogen" -I"C:\Users\Mukarram Saeed\SimplicityStudio\v5_workspace\Test1" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32MG21/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/i2cspm/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/Mukarram Saeed/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse -c -fmessage-length=0 -MMD -MP -MF"ssd1306.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


